quarkus.goblin.enabled=true
quarkus.goblin.assault.type=latency
quarkus.goblin.assault.latency.min-milliseconds=100
quarkus.goblin.assault.latency.max-milliseconds=500
quarkus.goblin.target.level=100
